# Generated by Django 3.1.7 on 2021-05-20 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='src',
            new_name='source',
        ),
    ]
